"""Model-agnostic dense retrieval and reranking interfaces."""

from .candidate_fusion import (
    CandidateInput,
    CandidateSelection,
    CandidateSetOracleAnalysis,
    CandidateSetOracleObservation,
    FusionConfig,
    StructuredFeatures,
    evaluate_candidate_set_oracle,
)
from .dense import (
    BiEncoder,
    CandidateMetadata,
    CandidateModelAssembly,
    ConceptEncoder,
    CrossEncoderReranker,
    DenseRetrievalRequest,
    DevicePrecisionConfig,
    LinkingModelConfig,
    LinkingModelRegistry,
    LinkingRuntime,
    MentionEncoder,
    VectorIndex,
    assemble_linking_runtime,
)
from .ontology import (
    GateConfig,
    OntologyConcept,
    OntologyMode,
    OntologyRequest,
    OntologyReranker,
    OntologyRerankerConfig,
    OntologyRerankResult,
    OntologySnapshot,
    ScoreAdjustments,
    ScoreAdjustmentTrace,
)

__all__ = [
    "BiEncoder",
    "CandidateModelAssembly",
    "CandidateMetadata",
    "CandidateInput",
    "CandidateSelection",
    "CandidateSetOracleAnalysis",
    "CandidateSetOracleObservation",
    "ConceptEncoder",
    "CrossEncoderReranker",
    "DenseRetrievalRequest",
    "DevicePrecisionConfig",
    "FusionConfig",
    "GateConfig",
    "LinkingModelConfig",
    "LinkingModelRegistry",
    "LinkingRuntime",
    "MentionEncoder",
    "OntologyConcept",
    "OntologyMode",
    "OntologyRerankResult",
    "OntologyReranker",
    "OntologyRerankerConfig",
    "OntologyRequest",
    "OntologySnapshot",
    "ScoreAdjustmentTrace",
    "ScoreAdjustments",
    "StructuredFeatures",
    "VectorIndex",
    "assemble_linking_runtime",
    "evaluate_candidate_set_oracle",
]
